name: Build documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/source/**'
      - 'docs/assets/**'
      - 'optimum/**'
      - '.github/workflows/doc-build.yml'

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: optimum-neuron
      package_name: optimum.neuron
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}