name: Build PR Documentation

on:
  pull_request:
    paths:
      - 'docs/source/**'
      - 'docs/assets/**'
      - 'optimum/**'
      - '.github/workflows/doc-pr-build.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@main
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: optimum-neuron
      package_name: optimum.neuron
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}